language: go

go:
  - "1.13"
  - "1.14"
  - "master"

matrix:
  allow_failures:
    - go: "master"

branches:
  only:
    - latest

env:
  - GO111MODULE=on

services:
  - docker

install:
  - go mod tidy
  - golangci-lint --version || curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.25.0

script:
  - golangci-lint run
  - go test ./...
  - make build TAGNAME=$(printenv TRAVIS_BRANCH)
  - make run TAGNAME=$(printenv TRAVIS_BRANCH)
  - sleep 2
  - "curl -X POST http://localhost:8080 -H 'Authorization: Basic dXNlcjpwYXNzd29yZA==' | grep 'Invalid API key'"

after_success:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then
    printenv DOCKERHUB_PASSWORD | docker login --username nstapelbroekbot --password-stdin;
    docker tag nstapelbroek/gatekeeper:$TRAVIS_BRANCH docker.io/nstapelbroek/gatekeeper:$TRAVIS_BRANCH;
    docker push docker.io/nstapelbroek/gatekeeper;
    fi
