language: go

go:
  - "1.10"

services:
  - docker

env:
  - DEP_VERSION="0.4.1"

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep && chmod +x $GOPATH/bin/dep
  - go get -u golang.org/x/lint/golint

install:
  - dep ensure

script:
  - golint -set_exit_status -min_confidence=0.9 $(go list ./... | grep -v /vendor/)
  - go test ./...
  - make build TAGNAME=$(printenv TRAVIS_BRANCH)
  - make run TAGNAME=$(printenv TRAVIS_BRANCH)
  - sleep 2
  - "curl -X POST http://localhost:8080 -H 'Authorization: Basic dXNlcjpwYXNzd29yZA==' | grep 'Failed whitelisting'"

after_success:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then
      docker login -u="nstapelbroekbot" -p="$DOCKERHUB_PASSWORD";
      docker tag nstapelbroek/gatekeeper:$TRAVIS_BRANCH docker.io/nstapelbroek/gatekeeper:$TRAVIS_BRANCH;
      docker push docker.io/nstapelbroek/gatekeeper;
    fi
