language: go

go:
  - "1.12"

services:
  - docker

env:
  - DEP_VERSION="0.5.0"

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep && chmod +x $GOPATH/bin/dep
  - go get -u golang.org/x/lint/golint

install:
  - dep ensure
  - golangci-lint --version || curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.12.5

script:
  - golangci-lint run
  - go test ./...
  - make build TAGNAME=$(printenv TRAVIS_BRANCH)
  - make run TAGNAME=$(printenv TRAVIS_BRANCH)
  - sleep 2
  - "curl -X POST http://localhost:8080 -H 'Authorization: Basic dXNlcjpwYXNzd29yZA==' | grep 'Invalid API key'"

after_success:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then
    docker login -u="nstapelbroekbot" -p="$DOCKERHUB_PASSWORD";
    docker tag nstapelbroek/gatekeeper:$TRAVIS_BRANCH docker.io/nstapelbroek/gatekeeper:$TRAVIS_BRANCH;
    docker push docker.io/nstapelbroek/gatekeeper;
    fi
