[[constraint]]
  name = "github.com/JamesClonk/vultr"
  version = "2.0.0"

[[constraint]]
  name = "github.com/digitalocean/godo"
  version = "1.15.0"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.4.0"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.4.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.10.0"

[prune]
  go-tests = true
  unused-packages = true
